import Navbar from "@/components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import ClientOnly from "@/components/ClientOnly";
import SeatModal from "@/components/modals/SeatModals";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ClientOnly>
          <Navbar />
          <SeatModal />
          <div>{children}</div>
          <div id="portals"></div>
        </ClientOnly>
      </body>
    </html>
  );
}
